Fix pgrx install will case postgresql coredump
pgcentralfoundation/pgrx pull request #1263
Opened 2023-08-17 10:56 UTC by Sasasu

this is because pgrx will overwrite the .so file in place.

dlopen will use mmap with MAP_PRIVATE. but if other process is modifying the file.

dlopen will use MAP_PRIVATE to open the file and map a read-only memory use mmap(2). usually this memory has copy-on-write. if others is modifying the file. the previously mapped memory should not change.

but there is a undefined behavior, from man mmap(2):

```
MAP_PRIVATE: It is unspecified whether changes made to the file after the mmap()
call are visible in the mapped region.
```

what actually happens is that the read-only memory in postgresql is modified, and all pointers in the .TEXT segment is mashed up. the call stack looks like

```
 #0  0x0000000000731510 in ?? ()
 #1  0x00007f7a94515132 in core::sync::atomic::AtomicUsize::store (self=0x7f7a95110318 <pgrx_pg_sys::submodules::thread_check::ACTIVE_THREAD::h60448dcb81097e92>, val=0, order=core::sync::atomic::Ordering::Relaxed) at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/sync/atomic.rs:2291
 #2  0x00007f7a944f574b in pgrx_pg_sys::submodules::thread_check::init_active_thread::clear_in_child () at src/submodules/thread_check.rs:39
 #3  0x00007f7a962f8a88 in __run_postfork_handlers (who=who@entry=atfork_run_child, do_locking=do_locking@entry=false, lastrun=lastrun@entry=2) at register-atfork.c:187
 #4  0x00007f7a962df773 in __libc_fork () at fork.c:109
 #5  0x00005555e66ad948 in fork_process () at fork_process.c:61
 #6  0x00005555e66a5d48 in StartAutoVacWorker () at autovacuum.c:1543
 #7  0x00005555e66c43f7 in StartAutovacuumWorker () at postmaster.c:6155
 #8  0x00005555e66c3d21 in sigusr1_handler (postgres_signal_arg=10) at postmaster.c:5820
 #9  <signal handler called>
 #10 0x00007f7a9630eb84 in __GI___select (nfds=6, readfds=0x7ffc61c2fa40, writefds=0x0, exceptfds=0x0, timeout=0x7ffc61c2f9b0) at ../sysdeps/unix/sysv/linux/select.c:69
 #11 0x00005555e66be343 in ServerLoop () at postmaster.c:1950
 #12 0x00005555e66bdb0f in PostmasterMain (argc=5, argv=0x5555e8fb5490) at postmaster.c:1631
 #13 0x00005555e6560e41 in main (argc=5, argv=0x5555e8fb5490) at main.c:240
```

the is `pgrx_pg_sys` try to run the postfork hook. but the variable `ACTIVE_THREAD` and the code binary does not in the previous place.

2023-08-17 11:02 UTC, workingjubilee commented
Wow that's cursed.

2023-08-17 11:18 UTC, workingjubilee commented
Hmm, can you give more exact repro instructions?

2023-08-17 11:22 UTC, Sasasu commented
1. run `cargo pgrx install`
2. set `shared_preload_libraries = <the pgrx project>`
3. reboot PostgreSQL to take effect
4.  run `cargo pgrx install`, and wait for auto vacuum or create a new session.
5. PostgreSQL crash

sorry I forget to mention the repro need `shared_preload_libraries`

2023-08-17 11:24 UTC, Sasasu commented
also need make sure `init_active_thread()` is initialized. add a rust UDF call between <3> and <4>

2023-08-18 01:32 UTC, beeender commented
> run cargo pgrx install, and wait for auto vacuum or create a new session.

I think it can be reproduced by simply creating any new session, like `psql xxx`.

2023-08-18 02:32 UTC, Sasasu commented
https://github.com/postgresml/postgresml/issues/530

This guy copy the .so file. and get crashed on every UDF call. after rebooting PostgreSQL it returns to normal.
this PR can fix that issues.

2023-08-19 18:44 UTC, eeeebbbbrrrr requested changes

2023-08-19 18:44 UTC, eeeebbbbrrrr commented on cargo-pgrx/src/command/install.rs
> +        if cfg!(target_os = "macos") || cfg!(target_os = "linux") {
It seems to me we should just always do it this way, keeping the comments as to why.  macos and linux are our two primary target platforms and if they both exhibit similar problems with overwriting the existing .so, I'm sure other platforms do too.

2023-08-20 11:56 UTC, Sasasu commented
BTW, have you reproduced the problem?

I find `install(1)` will also remove the .so file before creating it.

```
touch a b
strace -e newfstatat,openat,unlinkat,ioctl install a b  

openat(AT_FDCWD, "b", O_RDONLY|O_PATH|O_DIRECTORY) = -1 ENOTDIR (Not a directory)
newfstatat(AT_FDCWD, "a", {st_mode=S_IFREG|0644, st_size=4, ...}, 0) = 0
newfstatat(AT_FDCWD, "b", {st_mode=S_IFREG|0755, st_size=4, ...}, AT_SYMLINK_NOFOLLOW) = 0
unlinkat(AT_FDCWD, "b", 0)              = 0
openat(AT_FDCWD, "a", O_RDONLY)         = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=4, ...}, AT_EMPTY_PATH) = 0
openat(AT_FDCWD, "b", O_WRONLY|O_CREAT|O_EXCL, 0600) = 4
ioctl(4, BTRFS_IOC_CLONE or FICLONE, 3) = 0
```

2023-08-22 21:20 UTC, workingjubilee commented
That is exciting.

2023-08-23 01:31 UTC, workingjubilee commented
```
2023-08-22 18:28:34.336 PDT [395747] LOG:  from bgworker: (Some("Hi"), Some(8), Some("(8,42)"))
2023-08-22 18:28:34.336 PDT [395747] LOG:  from bgworker: (Some("Hi"), Some(9), Some("(9,42)"))
2023-08-22 18:28:34.336 PDT [395747] LOG:  from bgworker: (Some("Hi"), Some(10), Some("(10,42)"))
2023-08-22 18:28:44.634 PDT [395740] LOG:  background worker "bgworkers" (PID 395747) was terminated by signal 11: Segmentation fault
2023-08-22 18:28:44.634 PDT [395740] LOG:  terminating any other active server processes
2023-08-22 18:28:44.733 PDT [395740] LOG:  statistics collector process (PID 395746) was terminated by signal 11: Segmentation fault
2023-08-22 18:28:44.733 PDT [395740] LOG:  all server processes terminated; reinitializing
2023-08-22 18:28:45.054 PDT [395740] LOG:  startup process (PID 398010) was terminated by signal 11: Segmentation fault
2023-08-22 18:28:45.054 PDT [395740] LOG:  aborting startup due to startup process failure
2023-08-22 18:28:45.069 PDT [395740] LOG:  database system is shut down
```

Successful repro.

There seems to have been more than just one segfault, even. Great. Excellent. Fantastic. Merging this and I will look into a regression test after we expand cargo-pgrx's capabilities a bit to make such easier.

2023-08-23 01:33 UTC, merged