Fixed conversion of i64 and f64 to datums on 32-bit machines
pgcentralfoundation/pgrx pull request #1859
Opened 2024-09-12 20:09 UTC by YohDeadfall

No tests in CI at the moment because GitHub Actions are .NET based which: actions/runner/issues/1181. May spend some time later on that, but for now let's keep the warning about official support of x64 only.

2024-09-12 20:17 UTC, workingjubilee commented
I will accept this if you also run down places like https://github.com/pgcentralfoundation/pgrx/blob/b810e98c27f32bd498c52e9e281dce5cfac1f0a0/pgrx/src/datum/array.rs#L569

2024-09-12 20:19 UTC, workingjubilee commented
Actually that specific place may be harmless even, but the point is that there's location that make assumptions about sizes.

2024-09-12 20:24 UTC, workingjubilee commented
I realize "search for all instances of the number 8 and make sure they aren't obviously bad" is a lot of effort but...

2024-09-12 20:33 UTC, YohDeadfall commented
> I realize "search for all instances of the number 8 and make sure they aren't obviously bad" is a lot of effort but...

That's fine, it requires checking only the `src` directory with focus mostly on datums which are untyped.

2024-09-13 09:00 UTC, YohDeadfall commented
According to the PostgreSQL source code `float8` type metadata reflects its storage with depednency on the architecture:

* https://github.com/postgres/postgres/blob/2b67bdca529c6aed4303eb6963d09d1b540137b8/src/include/c.h#L632-L636
* https://github.com/postgres/postgres/blob/2b67bdca529c6aed4303eb6963d09d1b540137b8/src/include/catalog/pg_type.dat#L223-L228

That implies that on 32-bit architectures the following code will always fall onto `ByRef` arm:

https://github.com/pgcentralfoundation/pgrx/blob/b810e98c27f32bd498c52e9e281dce5cfac1f0a0/pgrx/src/datum/array.rs#L108-L122

Moreover, `FixedSizeByVal<8>` cannot be used on a platform different from 64-bit.

2024-09-13 09:15 UTC, YohDeadfall commented
> I realize "search for all instances of the number 8 and make sure they aren't obviously bad" is a lot of effort but...

`grep -r --include=*.rs --exclude-dir=*build* --exclude-dir=*sys* 8` gave nothing which should be addressed.

2024-09-13 20:12 UTC, workingjubilee commented
Cool.

2024-09-13 20:18 UTC, workingjubilee requested changes

2024-09-13 20:18 UTC, workingjubilee commented on pgrx-pg-sys/src/submodules/datum.rs
> +            Datum::from(Box::into_raw(Box::new(val)))
This needs to be a palloc.

2024-09-13 20:18 UTC, workingjubilee commented on pgrx-pg-sys/src/submodules/datum.rs
> +            Datum::from(Box::into_raw(Box::new(val)))
This needs to be a palloc.

2024-09-13 20:19 UTC, workingjubilee commented on README.md
> + ⹋ PGRX has not been tested to work on 32-bit, but the library correcly handles conversion of `pg_sys::Datum`
Let's be honest about whether something is "correct" if it isn't tested.
```suggestion
 ⹋ PGRX has not been tested to work on 32-bit, but the library attempts to handle conversion of `pg_sys::Datum`
```

2024-09-14 19:15 UTC, YohDeadfall commented
`cargo c pg16` works fine after switching to `palloc`, but `cargo t pg16` fails with the following error:

```
   Compiling pgrx-pg-sys v0.12.4 (/home/yoh/src/pgrx/pgrx-pg-sys)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/yoh/.local/share/gem/ruby/3.2.0/bin:/home/yoh/.omnisharp:/home/yoh/.dotnet:/home/yoh/.cargo/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" VSLANG="1033" "cc" "-m64" "/tmp/rustcvAjAu0/symbols.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.05sgmwhndq4y1l1r41rtbyc9b.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.1jgziobn4hnx5ujmcyv2fxyle.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.24r5mew6nkwbgedrmjqn5lw7v.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.2ajt5s6rwycmdxuppsyhajine.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.2fn00kma6itcxx8hed2nnn947.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.2s8s4pged4gi5s56dq2854313.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.2y35exsw3m92lmwfu8bft765h.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.2ykipamv4nift36syqjpxshg7.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.31ceew8ouxbfzxrs58h3yzv2k.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.31qz2up61rbukowceh1k2htra.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.38zkyn0i44ujjt8ow6e59e3hb.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.3c6ry4nqvefq1996g272ojwnz.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.3pr19u8h2f63j6n62udnl8nhy.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.3s557tgohs38xpg7mkfzm823k.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.49js0rmf38wri1hmcpefkf77z.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.4jaebo631oulu1exf61f4k7k0.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.4k5r86gjc4ogqkjtesug2c68c.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.5a3zouhnlmtf5xg6lz514oa2f.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.6wi9s10taonpuik864zxk74cr.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.72papy3wycjvfmse3qptlm7a5.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.7a3bkhakow3p9wga4eli1r1l2.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.7lq87x70vpl0gunarvhjkqvpy.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.8kmn0vglx491xtof3826o6yuh.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.8rltmltm2g8t3b8d2f0r1vmzv.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.8wj3pbq7lvn44f7zeob0z7g9r.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.93gz3ft3zbj7ou3usbzo3oi4j.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.97ycbal66ova7uzssztfd5rxe.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.9891s5ayrwh5kqiau2fa7abyl.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.9ri5ot38rbv8xyzq2gdi8acrj.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.9yhuf5xrvw6roiwe9ypmblcjv.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.a9l3vair1cukr1e49o8l1qu7m.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.am6cfo3hddiv7ewhaxx1r29as.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.b4y6v0dheovm0eomu9ovvcpub.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.b9wxs6f3uymf5n0on0fubs2tl.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.baxm1fzsgztqn9as04jg9wh5h.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.bc5v92c7c6tx9o8c967vfvn4x.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.bgq1mlsg12hwzwobyz6le41jj.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.blz27pyppjwq68343ifkgmt9o.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.bs123mo9osxl0tl4o27wr115t.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.c3jd1ravw6gvldwauhhv4ellb.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.chzfcz2hsw9vkrrfipg6mlsp1.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.cj2lu15glttea3ouiwi4vbxmn.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.crn3gdpykv3awwu248pggyea0.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.ct2egluy0asg6nrjbhyucfyc8.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.ctwm5v79v7dh2frdkq5opm3vb.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.d2rixsmwqllgdrjpri75lbqqg.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.daxdtiduh4how4o0xhk98fbv5.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.dj0ithp59j8n9egkc56k6dl1j.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.dk884qjmle32ldejkb85nvapj.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.dohmc1y5ndnlpy5s8kbktek28.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.draha1547jdyqbapf9d8mdxh0.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.dx9a0wzhtezbb5s8znanho1fl.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.e21kvq9z2uv0fe0erf3vzqkvf.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.e6esj70kbisf0w4zzx42e37yk.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.e6isuuaztqwzfnyzive8co0sz.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.epeyqaf7j49k79uesnnnascmz.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.etzjiysyuvpg0dg1n74ocamqq.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.ezrl34gxkcao21llyly2cawyt.rcgu.o" "/home/yoh/src/pgrx/target/debug/deps/pgrx_pg_sys-ccf40e22fbf97d0e.3cvohq68ql3wwpk2isougx3f7.rcgu.o" "-Wl,--as-needed" "-L" "/home/yoh/src/pgrx/target/debug/deps" "-L" "/home/yoh/src/pgrx/target/debug/build/pgrx-pg-sys-f298184b10bba90c/out/cshim" "-L" "/home/yoh/src/pgrx/target/debug/build/cee-scape-14df383b0b34067e/out" "-L" "/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bdynamic" "-lresolv" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lpgrx-cshim-16" "-Wl,--no-whole-archive" "/home/yoh/src/pgrx/target/debug/deps/libsptr-098575f08333f30e.rlib" "/home/yoh/src/pgrx/target/debug/deps/libserde-3bc16b1a59055395.rlib" "/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-95407a28b34cb7d8.rlib" "/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-6cf033bd0623f965.rlib" "/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-92be448731e25aff.rlib" "/home/yoh/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-9c68449f4da60201.rlib" "/home/yoh/src/pgrx/target/debug/deps/libpgrx_sql_entity_graph-56bfcb03d2a9c76 [...]

2024-09-14 20:26 UTC, workingjubilee commented
we probably have unit tests that don't happen inside `#[pg_test]` for this

2024-09-14 20:31 UTC, workingjubilee requested changes
final nit, sorry.

We can fix the palloc thing for now by doing a `#[cfg(target_pointer_width)]` and running down the test later, or you can go hunt down the test.

2024-09-14 20:31 UTC, workingjubilee commented on pgrx-pg-sys/src/submodules/datum.rs
> +        if size_of::<i64>() <= size_of::<usize>() {
```suggestion
        if size_of::<i64>() <= size_of::<Datum>() {
```

2024-09-14 20:31 UTC, workingjubilee commented on pgrx-pg-sys/src/submodules/datum.rs
> +        if size_of::<u64>() <= size_of::<usize>() {
```suggestion
        if size_of::<u64>() <= size_of::<Datum>() {
```

2024-09-14 20:31 UTC, workingjubilee commented on pgrx/src/datum/from.rs
> +            let value = if size_of::<i64>() <= size_of::<usize>() {
```suggestion
            let value = if size_of::<i64>() <= size_of::<pg_sys::Datum>() {
```

2024-09-14 20:31 UTC, workingjubilee commented on pgrx/src/datum/from.rs
> +            let value = if size_of::<i64>() <= size_of::<usize>() {
```suggestion
            let value = if size_of::<f64>() <= size_of::<pg_sys::Datum>() {
```

2024-09-16 14:28 UTC, YohDeadfall commented
The `roundtrip_integers` test from `pgrx-pg-sys` breaks the build.

2024-09-17 02:09 UTC, workingjubilee commented
sigh.

2024-09-17 02:20 UTC, workingjubilee commented
Either the tests need to be moved out into pgrx-tests in a `#[pg_test]` or the code needs to change to be a `cfg` on `target_pointer_width`.

2024-09-17 09:45 UTC, YohDeadfall commented
Decided to go with `cfg` for now, but later it can be moved I guess to make `pg_sys::Datum` as simple as possible and less developer friendly. That should stimulate the move to `Datum<'scr>`.

2024-09-18 02:56 UTC, workingjubilee commented
This seems viable-enough for now.

2024-09-18 02:56 UTC, merged